network.host: 0.0.0.0

cluster.name: elasticsearch

node.name: crud_node

# Enable security features (if you have an Elastic license or are using Elastic Stack security features).
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/elasticsearch.key
xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/elasticsearch.crt
