# /etc/metricbeat/metricbeat.yml
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
# ============================== Metricbeat Autodiscover ==============================
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # Optionally, specify the Docker API endpoint
      host: "unix:///var/run/docker.sock"
      # If running Metricbeat in a Docker container, you might need:
      host: "unix:///hostfs/var/run/docker.sock"
metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - memory
    - network
    - filesystem
    - diskio
    - load
    - uptime
  enabled: true
  processors:
    - add_host_metadata: ~
    - add_cloud_metadata: ~
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

# ============================== Elasticsearch output ==============================
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]  # Replace with your Elasticsearch host and port

# =============================== Kibana =====================================
setup.kibana:
  host: "http://kibana:5601"  # Replace with your Kibana host and port

# ============================== Logging ==============================
# Optional logging configuration to help with troubleshooting.
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644

