# /etc/metricbeat/metricbeat.yml
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ============================== Metricbeat Autodiscover ==============================
# metricbeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true
#       # Optionally, specify the Docker API endpoint
#       host: "unix:///var/run/docker.sock"
#       # If running Metricbeat in a Docker container, you might need:
#       #host: "unix:///hostfs/var/run/docker.sock"
# metricbeat.modules:
# - module: system
#   period: 10s
#   metricsets:
#     - cpu
#     - memory
#     - network
#     - filesystem
#     - diskio
#     - load
#     - uptime
#   enabled: true
  processors:
    - add_host_metadata: 
      netinfo.enabled: true
    - add_cloud_metadata: ~

# ============================== Elasticsearch output ==============================
output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  username: "elastic"
  password: "Uday@123"
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/elasticsearch.crt"]

setup.template.name: "metricbeat-7.9.2"
setup.template.pattern: "metricbeat-7.9.2-*"
setup.template.enabled: true
setup.ilm.enabled: true
setup.ilm.policy_name: "metricbeat"
setup.ilm.rollover_alias: "metricbeat-7.9.2"
#above wil create a index with index name metricbeat-7.9.2-<date>-000001 and rollover the new index when lifeycle policy rule is satisfied

# =============================== Kibana =====================================
setup.kibana:
  host: "https://kibana:5601"
  username: "elastic"
  password: "Uday@123"
  ssl.verification_mode: "full"  # Replaces "certificate"
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/kibana.crt"]



# ============================== Logging ==============================
# Optional logging configuration to help with troubleshooting.
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644

