# /etc/metricbeat/metricbeat.yml
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ============================== Metricbeat Autodiscover ==============================
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # Optionally, specify the Docker API endpoint
      host: "unix:///var/run/docker.sock"
      # If running Metricbeat in a Docker container, you might need:
      #host: "unix:///hostfs/var/run/docker.sock"
metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - memory
    - network
    - filesystem
    - diskio
    - load
    - uptime
  enabled: true
  processors:
    - add_host_metadata: ~
    - add_cloud_metadata: ~

# ============================== Elasticsearch output ==============================
output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  username: "elastic"
  password: "Uday@123"
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/elasticsearch.crt"]
  indices:
  - index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}" # Default pattern
    when.contains:
      event.dataset: "system.cpu" # Optional condition for specific dataset
  - index: "metricbeat-index-%{+yyyy.MM.dd}" # Example custom index
    when.equals:
      metricset.name: "memory" # Optional condition for specific metricset

# Setup to load the template
setup.template:
  enabled: true
  name: "metricbeat"
  pattern: "metricbeat-*"
  overwrite: false

# Set the default index lifecycle policy
setup.ilm.enabled: true
setup.ilm.policy_name: "7-days-default"
setup.ilm.rollover_alias: "metricbeat"
setup.ilm.pattern: "{now/d}-000001"
# =============================== Kibana =====================================
setup.kibana:
  host: "https://kibana:5601"
  username: "elastic"
  password: "Uday@123"
  ssl.verification_mode: "full"  # Replaces "certificate"
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/kibana.crt"]



# ============================== Logging ==============================
# Optional logging configuration to help with troubleshooting.
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644

